package com.example.brainbites.ui.util

import android.content.Context
import android.content.Intent
import android.widget.Toast
import com.example.brainbites.data.BiteItem
import java.text.SimpleDateFormat
import java.util.*

object ExportUtils {
    fun exportFavoritesToText(context: Context, favorites: List<BiteItem>) {
        if (favorites.isEmpty()) {
            Toast.makeText(context, "No favorites to export", Toast.LENGTH_SHORT).show()
            return
        }

        val timestamp = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())
        val sb = StringBuilder()
        
        sb.append("🧠 BRAINBITES - MY SAVED INSIGHTS\n")
        sb.append("Exported on: $timestamp\n")
        sb.append("Total Facts: ${favorites.size}\n")
        sb.append("==========================================\n\n")

        favorites.forEachIndexed { index, item ->
            sb.append("${index + 1}. ${item.title ?: "Psychology Insight"}\n")
            sb.append("Category: ${item.category.displayName}\n")
            sb.append("Insight: ${item.fact}\n")
            if (item.fullFact != null) {
                sb.append("Details: ${item.fullFact}\n")
            }
            sb.append("------------------------------------------\n\n")
        }

        sb.append("Generated by BrainBites App\n")
        sb.append("Feed Your Mind Daily.")

        val exportText = sb.toString()
        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "My BrainBites Favorites - $timestamp")
            putExtra(Intent.EXTRA_TEXT, exportText)
        }

        val chooser = Intent.createChooser(shareIntent, "Export My Favorites to...")
        context.startActivity(chooser)
    }
}
